-- COLLEGES
CREATE SEQUENCE college_seq START WITH 100;
CREATE OR REPLACE TRIGGER college_bir BEFORE INSERT ON colleges FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := college_seq.NEXTVAL; END;
/

-- DEPARTMENTS
CREATE SEQUENCE dept_seq START WITH 100;
CREATE OR REPLACE TRIGGER dept_bir BEFORE INSERT ON departments FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := dept_seq.NEXTVAL; END;
/

-- DEGREES
CREATE SEQUENCE degree_seq START WITH 100;
CREATE OR REPLACE TRIGGER degree_bir BEFORE INSERT ON degrees FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := degree_seq.NEXTVAL; END;
/

-- SPECIALIZATIONS
CREATE SEQUENCE spec_seq START WITH 100;
CREATE OR REPLACE TRIGGER spec_bir BEFORE INSERT ON specializations FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := spec_seq.NEXTVAL; END;
/

-- CAMPUSES
CREATE SEQUENCE campus_seq START WITH 100;
CREATE OR REPLACE TRIGGER campus_bir BEFORE INSERT ON campuses FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := campus_seq.NEXTVAL; END;
/

-- ROOMS
CREATE SEQUENCE room_seq START WITH 100;
CREATE OR REPLACE TRIGGER room_bir BEFORE INSERT ON rooms FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := room_seq.NEXTVAL; END;
/

-- USERS (Starts at 1000)
CREATE SEQUENCE user_seq START WITH 1000;
CREATE OR REPLACE TRIGGER user_bir BEFORE INSERT ON users FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := user_seq.NEXTVAL; END;
/

-- ADMINS
CREATE SEQUENCE admin_seq START WITH 10;
CREATE OR REPLACE TRIGGER admin_bir BEFORE INSERT ON admins FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := admin_seq.NEXTVAL; END;
/

-- TERMINALS
CREATE SEQUENCE terminal_seq START WITH 100;
CREATE OR REPLACE TRIGGER terminal_bir BEFORE INSERT ON terminals FOR EACH ROW WHEN (new.id IS NULL)
BEGIN :new.id := terminal_seq.NEXTVAL; END;
/
